from unittest import TestCase
from django.test.client import RequestFactory

from django_simple_error.factory import view_factory


class TestHandlerFactory(TestCase):
    """Tests for views generated by the handler factory"""

    def test_correct_status_code(self) -> None:
        """Test returned views render the correct error code"""

        http_request = RequestFactory().request()
        for status_code in (400, 403, 404, 500):
            view = view_factory(status_code).as_view()
            response = view(http_request)

            self.assertEqual(status_code, response.status_code)
            self.assertEqual(status_code, response.status_code)
