from unittest import skip

from django.test import TestCase
from django.test.client import RequestFactory

from django_simple_error.factory import view_factory


class TestHandlerFactory(TestCase):
    """Tests for views generated by the handler factory"""

    def setUp(self) -> None:
        self.test_error = 407
        self.handler = view_factory(self.test_error)

    @skip('')
    def test_correct_status_code(self) -> None:
        """Test returned views render the correct error code"""

        test_request = RequestFactory().get('some_path')
        response = self.handler.as_view().get(test_request)
        self.assertEqual(self.test_error, response.status_code)
