from django.test import TestCase
from django.test.client import RequestFactory

from source.apps.http_error_handling import views
from source.apps.http_error_handling.views import _handler_factory


class ViewDefinitions(TestCase):
    """Test views are defined for all HTTP error codes from 400 through 599"""

    def runTest(self) -> None:
        for i in range(400, 600):
            self.assertTrue(hasattr(views, f'handler{i}'))


class TestHandlerFactory(TestCase):
    """Tests for views generated by the handler factory"""

    def setUp(self) -> None:
        self.test_error = 407
        self.test_template = 'error_pages/error_page.html'
        self.handler = _handler_factory(self.test_template, self.test_error)

    def test_correct_status_code(self) -> None:
        """Test returned views render the correct error code"""

        test_request = RequestFactory().get('some_path')
        response = self.handler(test_request)
        self.assertEqual(self.test_error, response.status_code)
